### ISSUE TITLE
Issue installing on node v8.5

### ISSUE THREAD

**Issue by runk** [freethenation/node-nlopt#2]
Hey there, I've got an issue with installation on node v8.5:

```

  CC(target) Release/obj.target/nloptlib/nlopt-2.3/direct/DIRect.o
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/direct/direct_wrap.o
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/direct/DIRserial.o
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/direct/DIRsubrout.o
../nlopt-2.3/direct/DIRsubrout.c:505:10: warning: explicitly assigning value of variable of type 'integer' (aka 'int') to itself
      [-Wself-assign]
            pos = pos;
            ~~~ ^ ~~~
1 warning generated.
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/cdirect/cdirect.o
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/cdirect/hybrid.o
../nlopt-2.3/cdirect/hybrid.c:91:12: warning: 'nlopt_minimize' is deprecated [-Wdeprecated-declarations]
     ret = nlopt_minimize(p->local_alg, n, fcount, p,
           ^
../nlopt-2.3/api/nlopt.h:333:35: note: 'nlopt_minimize' has been explicitly marked deprecated here
     int maxeval, double maxtime) NLOPT_DEPRECATED;
                                  ^
../nlopt-2.3/api/nlopt.h:316:43: note: expanded from macro 'NLOPT_DEPRECATED'
#  define NLOPT_DEPRECATED __attribute__((deprecated))
                                          ^
1 warning generated.
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/praxis/praxis.o
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/luksan/plis.o
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/luksan/plip.o
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/luksan/pnet.o
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/luksan/mssubs.o
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/luksan/pssubs.o
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/crs/crs.o
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/mlsl/mlsl.o
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/mma/mma.o
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/mma/ccsa_quadratic.o
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/cobyla/cobyla.o
../nlopt-2.3/cobyla/cobyla.c:35:19: warning: unused variable 'rcsid' [-Wunused-const-variable]
static char const rcsid[] =
                  ^
1 warning generated.
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/newuoa/newuoa.o
../nlopt-2.3/newuoa/newuoa.c:184:9: warning: 'nlopt_minimize_constrained' is deprecated [-Wdeprecated-declarations]
         ret = nlopt_minimize_constrained(NLOPT_LD_MMA, *n, quad_model, &qmd,
               ^
../nlopt-2.3/api/nlopt.h:344:35: note: 'nlopt_minimize_constrained' has been explicitly marked deprecated here
     int maxeval, double maxtime) NLOPT_DEPRECATED;
                                  ^
../nlopt-2.3/api/nlopt.h:316:43: note: expanded from macro 'NLOPT_DEPRECATED'
#  define NLOPT_DEPRECATED __attribute__((deprecated))
                                          ^
../nlopt-2.3/newuoa/newuoa.c:1241:10: warning: 'nlopt_minimize_constrained' is deprecated [-Wdeprecated-declarations]
         return nlopt_minimize_constrained(NLOPT_LD_MMA, *n, lag, &ld,
                ^
../nlopt-2.3/api/nlopt.h:344:35: note: 'nlopt_minimize_constrained' has been explicitly marked deprecated here
     int maxeval, double maxtime) NLOPT_DEPRECATED;
                                  ^
../nlopt-2.3/api/nlopt.h:316:43: note: expanded from macro 'NLOPT_DEPRECATED'
#  define NLOPT_DEPRECATED __attribute__((deprecated))
                                          ^
2 warnings generated.
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/neldermead/nldrmd.o
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/neldermead/sbplx.o
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/auglag/auglag.o
../nlopt-2.3/auglag/auglag.c:155:23: warning: comparison of integers of different signs: 'int' and 'unsigned int' [-Wsign-compare]
               for (k = 0; k < d.h[i].m; ++k) {
                           ~ ^ ~~~~~~~~
../nlopt-2.3/auglag/auglag.c:166:23: warning: comparison of integers of different signs: 'int' and 'unsigned int' [-Wsign-compare]
               for (k = 0; k < d.fc[i].m; ++k) {
                           ~ ^ ~~~~~~~~~
../nlopt-2.3/auglag/auglag.c:214:23: warning: comparison of integers of different signs: 'int' and 'unsigned int' [-Wsign-compare]
               for (k = 0; k < d.h[i].m; ++k) {
                           ~ ^ ~~~~~~~~
../nlopt-2.3/auglag/auglag.c:227:23: warning: comparison of integers of different signs: 'int' and 'unsigned int' [-Wsign-compare]
               for (k = 0; k < d.fc[i].m; ++k) {
                           ~ ^ ~~~~~~~~~
4 warnings generated.
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/bobyqa/bobyqa.o
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/isres/isres.o
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/slsqp/slsqp.o
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/api/general.o
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/api/options.o
../nlopt-2.3/api/options.c:235:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
../nlopt-2.3/api/options.c:257:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
2 warnings generated.
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/api/optimize.o
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/api/deprecated.o
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/api/f77api.o
In file included from ../nlopt-2.3/api/f77api.c:103:
../nlopt-2.3/api/f77funcs.h:57:14: warning: 'nlopt_minimize_constrained' is deprecated [-Wdeprecated-declarations]
     *info = nlopt_minimize_constrained((nlopt_algorithm) *algorithm,
             ^
../nlopt-2.3/api/nlopt.h:344:35: note: 'nlopt_minimize_constrained' has been explicitly marked deprecated here
     int maxeval, double maxtime) NLOPT_DEPRECATED;
                                  ^
../nlopt-2.3/api/nlopt.h:316:43: note: expanded from macro 'NLOPT_DEPRECATED'
#  define NLOPT_DEPRECATED __attribute__((deprecated))
                                          ^
In file included from ../nlopt-2.3/api/f77api.c:103:
../nlopt-2.3/api/f77funcs.h:96:6: warning: 'nlopt_get_local_search_algorithm' is deprecated [-Wdeprecated-declarations]
     nlopt_get_local_search_algorithm(&deriv, &nonderiv, maxeval);
     ^
../nlopt-2.3/api/nlopt.h:361:25: note: 'nlopt_get_local_search_algorithm' has been explicitly marked deprecated here
                                             int *maxeval) NLOPT_DEPRECATED;
                                                           ^
../nlopt-2.3/api/nlopt.h:316:43: note: expanded from macro 'NLOPT_DEPRECATED'
#  define NLOPT_DEPRECATED __attribute__((deprecated))
                                          ^
In file included from ../nlopt-2.3/api/f77api.c:103:
../nlopt-2.3/api/f77funcs.h:104:6: warning: 'nlopt_set_local_search_algorithm' is deprecated [-Wdeprecated-declarations]
     nlopt_set_local_search_algorithm(deriv, nonderiv, *maxeval);
     ^
../nlopt-2.3/api/nlopt.h:364:24: note: 'nlopt_set_local_search_algorithm' has been explicitly marked deprecated here
                                             int maxeval) NLOPT_DEPRECATED;
                                                          ^
../nlopt-2.3/api/nlopt.h:316:43: note: expanded from macro 'NLOPT_DEPRECATED'
#  define NLOPT_DEPRECATED __attribute__((deprecated))
                                          ^
In file included from ../nlopt-2.3/api/f77api.c:103:
../nlopt-2.3/api/f77funcs.h:109:13: warning: 'nlopt_get_stochastic_population' is deprecated [-Wdeprecated-declarations]
     *pop = nlopt_get_stochastic_population();
            ^
../nlopt-2.3/api/nlopt.h:366:57: note: 'nlopt_get_stochastic_population' has been explicitly marked deprecated here
NLOPT_EXTERN(int) nlopt_get_stochastic_population(void) NLOPT_DEPRECATED;
                                                        ^
../nlopt-2.3/api/nlopt.h:316:43: note: expanded from macro 'NLOPT_DEPRECATED'
#  define NLOPT_DEPRECATED __attribute__((deprecated))
                                          ^
In file included from ../nlopt-2.3/api/f77api.c:103:
../nlopt-2.3/api/f77funcs.h:113:6: warning: 'nlopt_set_stochastic_population' is deprecated [-Wdeprecated-declarations]
     nlopt_set_stochastic_population(*pop);
     ^
../nlopt-2.3/api/nlopt.h:367:61: note: 'nlopt_set_stochastic_population' has been explicitly marked deprecated here
NLOPT_EXTERN(void) nlopt_set_stochastic_population(int pop) NLOPT_DEPRECATED;
                                                            ^
../nlopt-2.3/api/nlopt.h:316:43: note: expanded from macro 'NLOPT_DEPRECATED'
#  define NLOPT_DEPRECATED __attribute__((deprecated))
                                          ^
In file included from ../nlopt-2.3/api/f77api.c:114:
../nlopt-2.3/api/f77funcs.h:57:14: warning: 'nlopt_minimize_constrained' is deprecated [-Wdeprecated-declarations]
     *info = nlopt_minimize_constrained((nlopt_algorithm) *algorithm,
             ^
../nlopt-2.3/api/nlopt.h:344:35: note: 'nlopt_minimize_constrained' has been explicitly marked deprecated here
     int maxeval, double maxtime) NLOPT_DEPRECATED;
                                  ^
../nlopt-2.3/api/nlopt.h:316:43: note: expanded from macro 'NLOPT_DEPRECATED'
#  define NLOPT_DEPRECATED __attribute__((deprecated))
                                          ^
In file included from ../nlopt-2.3/api/f77api.c:114:
../nlopt-2.3/api/f77funcs.h:96:6: warning: 'nlopt_get_local_search_algorithm' is deprecated [-Wdeprecated-declarations]
     nlopt_get_local_search_algorithm(&deriv, &nonderiv, maxeval);
     ^
../nlopt-2.3/api/nlopt.h:361:25: note: 'nlopt_get_local_search_algorithm' has been explicitly marked deprecated here
                                             int *maxeval) NLOPT_DEPRECATED;
                                                           ^
../nlopt-2.3/api/nlopt.h:316:43: note: expanded from macro 'NLOPT_DEPRECATED'
#  define NLOPT_DEPRECATED __attribute__((deprecated))
                                          ^
In file included from ../nlopt-2.3/api/f77api.c:114:
../nlopt-2.3/api/f77funcs.h:104:6: warning: 'nlopt_set_local_search_algorithm' is deprecated [-Wdeprecated-declarations]
     nlopt_set_local_search_algorithm(deriv, nonderiv, *maxeval);
     ^
../nlopt-2.3/api/nlopt.h:364:24: note: 'nlopt_set_local_search_algorithm' has been explicitly marked deprecated here
                                             int maxeval) NLOPT_DEPRECATED;
                                                          ^
../nlopt-2.3/api/nlopt.h:316:43: note: expanded from macro 'NLOPT_DEPRECATED'
#  define NLOPT_DEPRECATED __attribute__((deprecated))
                                          ^
In file included from ../nlopt-2.3/api/f77api.c:114:
../nlopt-2.3/api/f77funcs.h:109:13: warning: 'nlopt_get_stochastic_population' is deprecated [-Wdeprecated-declarations]
     *pop = nlopt_get_stochastic_population();
            ^
../nlopt-2.3/api/nlopt.h:366:57: note: 'nlopt_get_stochastic_population' has been explicitly marked deprecated here
NLOPT_EXTERN(int) nlopt_get_stochastic_population(void) NLOPT_DEPRECATED;
                                                        ^
../nlopt-2.3/api/nlopt.h:316:43: note: expanded from macro 'NLOPT_DEPRECATED'
#  define NLOPT_DEPRECATED __attribute__((deprecated))
                                          ^
In file included from ../nlopt-2.3/api/f77api.c:114:
../nlopt-2.3/api/f77funcs.h:113:6: warning: 'nlopt_set_stochastic_population' is deprecated [-Wdeprecated-declarations]
     nlopt_set_stochastic_population(*pop);
     ^
../nlopt-2.3/api/nlopt.h:367:61: note: 'nlopt_set_stochastic_population' has been explicitly marked deprecated here
NLOPT_EXTERN(void) nlopt_set_stochastic_population(int pop) NLOPT_DEPRECATED;
                                                            ^
../nlopt-2.3/api/nlopt.h:316:43: note: expanded from macro 'NLOPT_DEPRECATED'
#  define NLOPT_DEPRECATED __attribute__((deprecated))
                                          ^
In file included from ../nlopt-2.3/api/f77api.c:129:
../nlopt-2.3/api/f77funcs.h:57:14: warning: 'nlopt_minimize_constrained' is deprecated [-Wdeprecated-declarations]
     *info = nlopt_minimize_constrained((nlopt_algorithm) *algorithm,
             ^
../nlopt-2.3/api/nlopt.h:344:35: note: 'nlopt_minimize_constrained' has been explicitly marked deprecated here
     int maxeval, double maxtime) NLOPT_DEPRECATED;
                                  ^
../nlopt-2.3/api/nlopt.h:316:43: note: expanded from macro 'NLOPT_DEPRECATED'
#  define NLOPT_DEPRECATED __attribute__((deprecated))
                                          ^
In file included from ../nlopt-2.3/api/f77api.c:129:
../nlopt-2.3/api/f77funcs.h:96:6: warning: 'nlopt_get_local_search_algorithm' is deprecated [-Wdeprecated-declarations]
     nlopt_get_local_search_algorithm(&deriv, &nonderiv, maxeval);
     ^
../nlopt-2.3/api/nlopt.h:361:25: note: 'nlopt_get_local_search_algorithm' has been explicitly marked deprecated here
                                             int *maxeval) NLOPT_DEPRECATED;
                                                           ^
../nlopt-2.3/api/nlopt.h:316:43: note: expanded from macro 'NLOPT_DEPRECATED'
#  define NLOPT_DEPRECATED __attribute__((deprecated))
                                          ^
In file included from ../nlopt-2.3/api/f77api.c:129:
../nlopt-2.3/api/f77funcs.h:104:6: warning: 'nlopt_set_local_search_algorithm' is deprecated [-Wdeprecated-declarations]
     nlopt_set_local_search_algorithm(deriv, nonderiv, *maxeval);
     ^
../nlopt-2.3/api/nlopt.h:364:24: note: 'nlopt_set_local_search_algorithm' has been explicitly marked deprecated here
                                             int maxeval) NLOPT_DEPRECATED;
                                                          ^
../nlopt-2.3/api/nlopt.h:316:43: note: expanded from macro 'NLOPT_DEPRECATED'
#  define NLOPT_DEPRECATED __attribute__((deprecated))
                                          ^
In file included from ../nlopt-2.3/api/f77api.c:129:
../nlopt-2.3/api/f77funcs.h:109:13: warning: 'nlopt_get_stochastic_population' is deprecated [-Wdeprecated-declarations]
     *pop = nlopt_get_stochastic_population();
            ^
../nlopt-2.3/api/nlopt.h:366:57: note: 'nlopt_get_stochastic_population' has been explicitly marked deprecated here
NLOPT_EXTERN(int) nlopt_get_stochastic_population(void) NLOPT_DEPRECATED;
                                                        ^
../nlopt-2.3/api/nlopt.h:316:43: note: expanded from macro 'NLOPT_DEPRECATED'
#  define NLOPT_DEPRECATED __attribute__((deprecated))
                                          ^
In file included from ../nlopt-2.3/api/f77api.c:129:
../nlopt-2.3/api/f77funcs.h:113:6: warning: 'nlopt_set_stochastic_population' is deprecated [-Wdeprecated-declarations]
     nlopt_set_stochastic_population(*pop);
     ^
../nlopt-2.3/api/nlopt.h:367:61: note: 'nlopt_set_stochastic_population' has been explicitly marked deprecated here
NLOPT_EXTERN(void) nlopt_set_stochastic_population(int pop) NLOPT_DEPRECATED;
                                                            ^
../nlopt-2.3/api/nlopt.h:316:43: note: expanded from macro 'NLOPT_DEPRECATED'
#  define NLOPT_DEPRECATED __attribute__((deprecated))
                                          ^
15 warnings generated.
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/util/mt19937ar.o
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/util/sobolseq.o
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/util/timer.o
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/util/stop.o
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/util/redblack.o
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/util/qsort_r.o
  CC(target) Release/obj.target/nloptlib/nlopt-2.3/util/rescale.o
  CXX(target) Release/obj.target/nloptlib/nlopt-2.3/stogo/global.o
  CXX(target) Release/obj.target/nloptlib/nlopt-2.3/stogo/linalg.o
  CXX(target) Release/obj.target/nloptlib/nlopt-2.3/stogo/local.o
  CXX(target) Release/obj.target/nloptlib/nlopt-2.3/stogo/stogo.o
  CXX(target) Release/obj.target/nloptlib/nlopt-2.3/stogo/tools.o
  LIBTOOL-STATIC Release/nloptlib.a
  CXX(target) Release/obj.target/nlopt/nlopt.o
../nlopt.cc:12:51: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'unsigned int'
  Local<Array> ret = Local<Array>::New(Array::New(n));
                                                  ^
/Users/username/.node-gyp/8.5.0/include/node/v8.h:3465:36: note: passing argument to parameter 'isolate' here
  static Local<Array> New(Isolate* isolate, int length = 0);
                                   ^
../nlopt.cc:15:37: error: too few arguments to function call, expected 2, have 1
    ret->Set(i, Number::New(array[i]));
                ~~~~~~~~~~~         ^
/Users/username/.node-gyp/8.5.0/include/node/v8.h:2857:3: note: 'New' declared here
  static Local<Number> New(Isolate* isolate, double value);
  ^
../nlopt.cc:73:34: error: no member named 'New' in 'v8::String'
  errors->Set(operation, String::New(str));
                         ~~~~~~~~^
../nlopt.cc:95:15: error: calling a protected constructor of class 'v8::HandleScope'
  HandleScope scope;
              ^
/Users/username/.node-gyp/8.5.0/include/node/v8.h:876:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../nlopt.cc:102:44: error: too few arguments to function call, expected 2, have 1
  argv[0] = Local<Value>::New(Number::New(n));
                              ~~~~~~~~~~~  ^
/Users/username/.node-gyp/8.5.0/include/node/v8.h:2857:3: note: 'New' declared here
  static Local<Number> New(Isolate* isolate, double value);
  ^
../nlopt.cc:111:33: error: no matching function for call to 'Null'
    argv[2] = Local<Value>::New(Null());
                                ^~~~
/Users/username/.node-gyp/8.5.0/include/node/v8.h:313:27: note: candidate function not viable: requires single argument 'isolate', but no
      arguments were provided
  friend Local<Primitive> Null(Isolate* isolate);
                          ^
../nlopt.cc:114:46: error: no member named 'GetCurrent' in 'v8::Context'
  Local<Value> ret = callback->Call(Context::GetCurrent()->Global(), 3, argv);
                                    ~~~~~~~~~^
../nlopt.cc:117:49: error: no member named 'New' in 'v8::String'
    ThrowException(Exception::TypeError(String::New("Objective or constraint function must return a number.")));
                                        ~~~~~~~~^
../nlopt.cc:120:49: error: no member named 'New' in 'v8::String'
    ThrowException(Exception::TypeError(String::New("Length of gradient array must be the same as the number of parameters.")));
                                        ~~~~~~~~^
../nlopt.cc:130:9: error: no member named 'Close' in 'v8::HandleScope'
  scope.Close(undefined);
  ~~~~~ ^
../nlopt.cc:134:30: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> Optimize(const Arguments& args) {
                             ^~~~~~~~~
                             v8::internal::Arguments
/Users/username/.node-gyp/8.5.0/include/node/v8.h:141:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../nlopt.cc:135:15: error: calling a protected constructor of class 'v8::HandleScope'
  HandleScope scope;
              ^
/Users/username/.node-gyp/8.5.0/include/node/v8.h:876:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../nlopt.cc:136:54: error: too few arguments to function call, single argument 'isolate' was not specified
  Local<Object> ret = Local<Object>::New(Object::New());
                                         ~~~~~~~~~~~ ^
/Users/username/.node-gyp/8.5.0/include/node/v8.h:3432:3: note: 'New' declared here
  static Local<Object> New(Isolate* isolate);
  ^
../nlopt.cc:141:51: error: type 'const v8::internal::Arguments' does not provide a subscript operator
  Local<Object> options = Local<Object>::Cast(args[0]);
                                              ~~~~^~
../nlopt.cc:144:3: error: no member named 'NewSymbol' in 'v8::String'
  GET_VALUE(Number, algorithm, options)
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../nlopt.cc:77:57: note: expanded from macro 'GET_VALUE'
  Local<String> key_##NAME = Local<String>::New(String::NewSymbol(#NAME)); \
                                                ~~~~~~~~^
../nlopt.cc:145:3: error: no member named 'NewSymbol' in 'v8::String'
  GET_VALUE(Number, numberOfParameters, options)
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../nlopt.cc:77:57: note: expanded from macro 'GET_VALUE'
  Local<String> key_##NAME = Local<String>::New(String::NewSymbol(#NAME)); \
                                                ~~~~~~~~^
../nlopt.cc:151:3: error: no member named 'NewSymbol' in 'v8::String'
  GET_VALUE(Function, minObjectiveFunction, options)
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../nlopt.cc:77:57: note: expanded from macro 'GET_VALUE'
  Local<String> key_##NAME = Local<String>::New(String::NewSymbol(#NAME)); \
                                                ~~~~~~~~^
../nlopt.cc:152:3: error: no member named 'NewSymbol' in 'v8::String'
  GET_VALUE(Function, maxObjectiveFunction, options)
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../nlopt.cc:77:57: note: expanded from macro 'GET_VALUE'
  Local<String> key_##NAME = Local<String>::New(String::NewSymbol(#NAME)); \
                                                ~~~~~~~~^
../nlopt.cc:162:49: error: no member named 'New' in 'v8::String'
    ThrowException(Exception::TypeError(String::New("minObjectiveFunction or maxObjectiveFunction must be specified")));
                                        ~~~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/nlopt/nlopt.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/username/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/username/.nvm/versions/node/v8.5.0/bin/node" "/Users/username/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/username/projects/deleteme/node_modules/nlopt
gyp ERR! node -v v8.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

**Comment by jkon** [comment]
@runk did you ever figure out a way to add nlopt to your project? I need a non-linear optimizer to use in a an angular project and I am getting these same errors trying to install this package.

**Comment by richardklafter** [comment]
Does this PR solve it for you https://github.com/freethenation/node-nlopt/pull/3?

**Comment by jkon** [comment]
Not sure. I don't know how to go about trying either. I haven't dug into
how to build a c library for use in an npm package yet. I did contact the
person who submitted that PR and he said that he got it to work, but
abandoned it in favor of a python library. I would much prefer a js library
as I need to use it in an Angular app. Could you test out the PR and merge
it if it works?
FYI, I am using node v10.16.1 and npm 6.14.5
Thanks,

Joshua P Kon
Email: joshuapkon@gmail.com

**Comment by runk** [comment]
@jkon I ended up using http://optimization-js.github.io/optimization-js/

**Comment by EvilDrW** [comment]
@jkon  I did try @daramasala's fork and got the same error that was originally reported in this thread.  I do have some experience building native npm modules and will see what I can do as I need this as well.

**Comment by jkon** [comment]
I ended up just learning python and using scipy for now. If you do figure this out, that would be great, but for now, I’m gonna write a backend service instead of trying to use this in a front end web worker

**Comment by EvilDrW** [comment]
I'm doing it in a backend service as well, but in node instead of python.

**Comment by freethenation** [comment]
Wow. It has been many years since I looked at this. I merged in @daramasala fork, tested that it worked, and published to NPM. Let me know if you have issues.
